//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: haru.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Service definition.
///
/// Usage: instantiate `Haru_version1Client`, then call methods of this protocol to make API calls.
internal protocol Haru_version1ClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Haru_version1ClientInterceptorFactoryProtocol? { get }

  func createAccount(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_AccountRequest, Haru_AccountReply>

  func getProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func updateProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func getPoint(
    _ request: Haru_PointRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_PointRequest, Haru_PointReply>

  func incrPoint(
    _ request: Haru_PointRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_PointRequest, Haru_PointReply>

  func getPlaceByID(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceReply>

  func getPlaceByInput(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceReply>

  func updatePlaceProfile(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply>

  func getPlaceProfile(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply>

  func getNearbySearch(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceReplyList>
}

extension Haru_version1ClientProtocol {
  internal var serviceName: String {
    return "haru.version1"
  }

  /// Create Account
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateAccount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createAccount(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_AccountRequest, Haru_AccountReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  /// GetProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to GetProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }

  /// UpdateProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? []
    )
  }

  /// GetPoint
  ///
  /// - Parameters:
  ///   - request: Request to send to GetPoint.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getPoint(
    _ request: Haru_PointRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_PointRequest, Haru_PointReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPoint.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPointInterceptors() ?? []
    )
  }

  /// IncrPoint
  ///
  /// - Parameters:
  ///   - request: Request to send to IncrPoint.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func incrPoint(
    _ request: Haru_PointRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_PointRequest, Haru_PointReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.incrPoint.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeIncrPointInterceptors() ?? []
    )
  }

  /// GetPlaceByID
  ///
  /// - Parameters:
  ///   - request: Request to send to GetPlaceByID.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getPlaceByID(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceByID.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceByIDInterceptors() ?? []
    )
  }

  /// GetPlaceByInput
  ///
  /// - Parameters:
  ///   - request: Request to send to GetPlaceByInput.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getPlaceByInput(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceByInput.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceByInputInterceptors() ?? []
    )
  }

  /// UpdatePlaceProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdatePlaceProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updatePlaceProfile(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updatePlaceProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePlaceProfileInterceptors() ?? []
    )
  }

  /// GetPlaceProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to GetPlaceProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getPlaceProfile(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceProfileInterceptors() ?? []
    )
  }

  /// getNearbySearch
  ///
  /// - Parameters:
  ///   - request: Request to send to GetNearbySearch.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getNearbySearch(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_PlaceRequest, Haru_PlaceReplyList> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getNearbySearch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetNearbySearchInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Haru_version1Client: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Haru_version1NIOClient")
internal final class Haru_version1Client: Haru_version1ClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Haru_version1ClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the haru.version1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Haru_version1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Haru_version1NIOClient: Haru_version1ClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol?

  /// Creates a client for the haru.version1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Haru_version1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Service definition.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Haru_version1AsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Haru_version1ClientInterceptorFactoryProtocol? { get }

  func makeCreateAccountCall(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_AccountRequest, Haru_AccountReply>

  func makeGetProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func makeUpdateProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func makeGetPointCall(
    _ request: Haru_PointRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_PointRequest, Haru_PointReply>

  func makeIncrPointCall(
    _ request: Haru_PointRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_PointRequest, Haru_PointReply>

  func makeGetPlaceByIDCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceReply>

  func makeGetPlaceByInputCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceReply>

  func makeUpdatePlaceProfileCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply>

  func makeGetPlaceProfileCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply>

  func makeGetNearbySearchCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceReplyList>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Haru_version1AsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Haru_version1ClientMetadata.serviceDescriptor
  }

  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCreateAccountCall(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_AccountRequest, Haru_AccountReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  internal func makeGetProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }

  internal func makeUpdateProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? []
    )
  }

  internal func makeGetPointCall(
    _ request: Haru_PointRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_PointRequest, Haru_PointReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPoint.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPointInterceptors() ?? []
    )
  }

  internal func makeIncrPointCall(
    _ request: Haru_PointRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_PointRequest, Haru_PointReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.incrPoint.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeIncrPointInterceptors() ?? []
    )
  }

  internal func makeGetPlaceByIDCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceByID.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceByIDInterceptors() ?? []
    )
  }

  internal func makeGetPlaceByInputCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceByInput.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceByInputInterceptors() ?? []
    )
  }

  internal func makeUpdatePlaceProfileCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updatePlaceProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePlaceProfileInterceptors() ?? []
    )
  }

  internal func makeGetPlaceProfileCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceProfileReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceProfileInterceptors() ?? []
    )
  }

  internal func makeGetNearbySearchCall(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_PlaceRequest, Haru_PlaceReplyList> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getNearbySearch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetNearbySearchInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Haru_version1AsyncClientProtocol {
  internal func createAccount(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_AccountReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  internal func getProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_ProfileReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }

  internal func updateProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_ProfileReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? []
    )
  }

  internal func getPoint(
    _ request: Haru_PointRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_PointReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPoint.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPointInterceptors() ?? []
    )
  }

  internal func incrPoint(
    _ request: Haru_PointRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_PointReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.incrPoint.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeIncrPointInterceptors() ?? []
    )
  }

  internal func getPlaceByID(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_PlaceReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceByID.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceByIDInterceptors() ?? []
    )
  }

  internal func getPlaceByInput(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_PlaceReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceByInput.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceByInputInterceptors() ?? []
    )
  }

  internal func updatePlaceProfile(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_PlaceProfileReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updatePlaceProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdatePlaceProfileInterceptors() ?? []
    )
  }

  internal func getPlaceProfile(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_PlaceProfileReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getPlaceProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPlaceProfileInterceptors() ?? []
    )
  }

  internal func getNearbySearch(
    _ request: Haru_PlaceRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_PlaceReplyList {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getNearbySearch.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetNearbySearchInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Haru_version1AsyncClient: Haru_version1AsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Haru_version1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Haru_version1ClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'createAccount'.
  func makeCreateAccountInterceptors() -> [ClientInterceptor<Haru_AccountRequest, Haru_AccountReply>]

  /// - Returns: Interceptors to use when invoking 'getProfile'.
  func makeGetProfileInterceptors() -> [ClientInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when invoking 'updateProfile'.
  func makeUpdateProfileInterceptors() -> [ClientInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when invoking 'getPoint'.
  func makeGetPointInterceptors() -> [ClientInterceptor<Haru_PointRequest, Haru_PointReply>]

  /// - Returns: Interceptors to use when invoking 'incrPoint'.
  func makeIncrPointInterceptors() -> [ClientInterceptor<Haru_PointRequest, Haru_PointReply>]

  /// - Returns: Interceptors to use when invoking 'getPlaceByID'.
  func makeGetPlaceByIDInterceptors() -> [ClientInterceptor<Haru_PlaceRequest, Haru_PlaceReply>]

  /// - Returns: Interceptors to use when invoking 'getPlaceByInput'.
  func makeGetPlaceByInputInterceptors() -> [ClientInterceptor<Haru_PlaceRequest, Haru_PlaceReply>]

  /// - Returns: Interceptors to use when invoking 'updatePlaceProfile'.
  func makeUpdatePlaceProfileInterceptors() -> [ClientInterceptor<Haru_PlaceRequest, Haru_PlaceProfileReply>]

  /// - Returns: Interceptors to use when invoking 'getPlaceProfile'.
  func makeGetPlaceProfileInterceptors() -> [ClientInterceptor<Haru_PlaceRequest, Haru_PlaceProfileReply>]

  /// - Returns: Interceptors to use when invoking 'getNearbySearch'.
  func makeGetNearbySearchInterceptors() -> [ClientInterceptor<Haru_PlaceRequest, Haru_PlaceReplyList>]
}

internal enum Haru_version1ClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "version1",
    fullName: "haru.version1",
    methods: [
      Haru_version1ClientMetadata.Methods.createAccount,
      Haru_version1ClientMetadata.Methods.getProfile,
      Haru_version1ClientMetadata.Methods.updateProfile,
      Haru_version1ClientMetadata.Methods.getPoint,
      Haru_version1ClientMetadata.Methods.incrPoint,
      Haru_version1ClientMetadata.Methods.getPlaceByID,
      Haru_version1ClientMetadata.Methods.getPlaceByInput,
      Haru_version1ClientMetadata.Methods.updatePlaceProfile,
      Haru_version1ClientMetadata.Methods.getPlaceProfile,
      Haru_version1ClientMetadata.Methods.getNearbySearch,
    ]
  )

  internal enum Methods {
    internal static let createAccount = GRPCMethodDescriptor(
      name: "CreateAccount",
      path: "/haru.version1/CreateAccount",
      type: GRPCCallType.unary
    )

    internal static let getProfile = GRPCMethodDescriptor(
      name: "GetProfile",
      path: "/haru.version1/GetProfile",
      type: GRPCCallType.unary
    )

    internal static let updateProfile = GRPCMethodDescriptor(
      name: "UpdateProfile",
      path: "/haru.version1/UpdateProfile",
      type: GRPCCallType.unary
    )

    internal static let getPoint = GRPCMethodDescriptor(
      name: "GetPoint",
      path: "/haru.version1/GetPoint",
      type: GRPCCallType.unary
    )

    internal static let incrPoint = GRPCMethodDescriptor(
      name: "IncrPoint",
      path: "/haru.version1/IncrPoint",
      type: GRPCCallType.unary
    )

    internal static let getPlaceByID = GRPCMethodDescriptor(
      name: "GetPlaceByID",
      path: "/haru.version1/GetPlaceByID",
      type: GRPCCallType.unary
    )

    internal static let getPlaceByInput = GRPCMethodDescriptor(
      name: "GetPlaceByInput",
      path: "/haru.version1/GetPlaceByInput",
      type: GRPCCallType.unary
    )

    internal static let updatePlaceProfile = GRPCMethodDescriptor(
      name: "UpdatePlaceProfile",
      path: "/haru.version1/UpdatePlaceProfile",
      type: GRPCCallType.unary
    )

    internal static let getPlaceProfile = GRPCMethodDescriptor(
      name: "GetPlaceProfile",
      path: "/haru.version1/GetPlaceProfile",
      type: GRPCCallType.unary
    )

    internal static let getNearbySearch = GRPCMethodDescriptor(
      name: "GetNearbySearch",
      path: "/haru.version1/GetNearbySearch",
      type: GRPCCallType.unary
    )
  }
}

/// Service definition.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Haru_version1Provider: CallHandlerProvider {
  var interceptors: Haru_version1ServerInterceptorFactoryProtocol? { get }

  /// Create Account
  func createAccount(request: Haru_AccountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_AccountReply>

  /// GetProfile
  func getProfile(request: Haru_ProfileRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_ProfileReply>

  /// UpdateProfile
  func updateProfile(request: Haru_ProfileRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_ProfileReply>

  /// GetPoint
  func getPoint(request: Haru_PointRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_PointReply>

  /// IncrPoint
  func incrPoint(request: Haru_PointRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_PointReply>

  /// GetPlaceByID
  func getPlaceByID(request: Haru_PlaceRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_PlaceReply>

  /// GetPlaceByInput
  func getPlaceByInput(request: Haru_PlaceRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_PlaceReply>

  /// UpdatePlaceProfile
  func updatePlaceProfile(request: Haru_PlaceRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_PlaceProfileReply>

  /// GetPlaceProfile
  func getPlaceProfile(request: Haru_PlaceRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_PlaceProfileReply>

  /// getNearbySearch
  func getNearbySearch(request: Haru_PlaceRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_PlaceReplyList>
}

extension Haru_version1Provider {
  internal var serviceName: Substring {
    return Haru_version1ServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateAccount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_AccountRequest>(),
        responseSerializer: ProtobufSerializer<Haru_AccountReply>(),
        interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? [],
        userFunction: self.createAccount(request:context:)
      )

    case "GetProfile":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeGetProfileInterceptors() ?? [],
        userFunction: self.getProfile(request:context:)
      )

    case "UpdateProfile":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? [],
        userFunction: self.updateProfile(request:context:)
      )

    case "GetPoint":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PointRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PointReply>(),
        interceptors: self.interceptors?.makeGetPointInterceptors() ?? [],
        userFunction: self.getPoint(request:context:)
      )

    case "IncrPoint":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PointRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PointReply>(),
        interceptors: self.interceptors?.makeIncrPointInterceptors() ?? [],
        userFunction: self.incrPoint(request:context:)
      )

    case "GetPlaceByID":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceReply>(),
        interceptors: self.interceptors?.makeGetPlaceByIDInterceptors() ?? [],
        userFunction: self.getPlaceByID(request:context:)
      )

    case "GetPlaceByInput":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceReply>(),
        interceptors: self.interceptors?.makeGetPlaceByInputInterceptors() ?? [],
        userFunction: self.getPlaceByInput(request:context:)
      )

    case "UpdatePlaceProfile":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceProfileReply>(),
        interceptors: self.interceptors?.makeUpdatePlaceProfileInterceptors() ?? [],
        userFunction: self.updatePlaceProfile(request:context:)
      )

    case "GetPlaceProfile":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceProfileReply>(),
        interceptors: self.interceptors?.makeGetPlaceProfileInterceptors() ?? [],
        userFunction: self.getPlaceProfile(request:context:)
      )

    case "GetNearbySearch":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceReplyList>(),
        interceptors: self.interceptors?.makeGetNearbySearchInterceptors() ?? [],
        userFunction: self.getNearbySearch(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

/// Service definition.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Haru_version1AsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Haru_version1ServerInterceptorFactoryProtocol? { get }

  /// Create Account
  @Sendable func createAccount(
    request: Haru_AccountRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_AccountReply

  /// GetProfile
  @Sendable func getProfile(
    request: Haru_ProfileRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_ProfileReply

  /// UpdateProfile
  @Sendable func updateProfile(
    request: Haru_ProfileRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_ProfileReply

  /// GetPoint
  @Sendable func getPoint(
    request: Haru_PointRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_PointReply

  /// IncrPoint
  @Sendable func incrPoint(
    request: Haru_PointRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_PointReply

  /// GetPlaceByID
  @Sendable func getPlaceByID(
    request: Haru_PlaceRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_PlaceReply

  /// GetPlaceByInput
  @Sendable func getPlaceByInput(
    request: Haru_PlaceRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_PlaceReply

  /// UpdatePlaceProfile
  @Sendable func updatePlaceProfile(
    request: Haru_PlaceRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_PlaceProfileReply

  /// GetPlaceProfile
  @Sendable func getPlaceProfile(
    request: Haru_PlaceRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_PlaceProfileReply

  /// getNearbySearch
  @Sendable func getNearbySearch(
    request: Haru_PlaceRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_PlaceReplyList
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Haru_version1AsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Haru_version1ServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Haru_version1ServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Haru_version1ServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateAccount":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_AccountRequest>(),
        responseSerializer: ProtobufSerializer<Haru_AccountReply>(),
        interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? [],
        wrapping: self.createAccount(request:context:)
      )

    case "GetProfile":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeGetProfileInterceptors() ?? [],
        wrapping: self.getProfile(request:context:)
      )

    case "UpdateProfile":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? [],
        wrapping: self.updateProfile(request:context:)
      )

    case "GetPoint":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PointRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PointReply>(),
        interceptors: self.interceptors?.makeGetPointInterceptors() ?? [],
        wrapping: self.getPoint(request:context:)
      )

    case "IncrPoint":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PointRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PointReply>(),
        interceptors: self.interceptors?.makeIncrPointInterceptors() ?? [],
        wrapping: self.incrPoint(request:context:)
      )

    case "GetPlaceByID":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceReply>(),
        interceptors: self.interceptors?.makeGetPlaceByIDInterceptors() ?? [],
        wrapping: self.getPlaceByID(request:context:)
      )

    case "GetPlaceByInput":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceReply>(),
        interceptors: self.interceptors?.makeGetPlaceByInputInterceptors() ?? [],
        wrapping: self.getPlaceByInput(request:context:)
      )

    case "UpdatePlaceProfile":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceProfileReply>(),
        interceptors: self.interceptors?.makeUpdatePlaceProfileInterceptors() ?? [],
        wrapping: self.updatePlaceProfile(request:context:)
      )

    case "GetPlaceProfile":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceProfileReply>(),
        interceptors: self.interceptors?.makeGetPlaceProfileInterceptors() ?? [],
        wrapping: self.getPlaceProfile(request:context:)
      )

    case "GetNearbySearch":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_PlaceRequest>(),
        responseSerializer: ProtobufSerializer<Haru_PlaceReplyList>(),
        interceptors: self.interceptors?.makeGetNearbySearchInterceptors() ?? [],
        wrapping: self.getNearbySearch(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

internal protocol Haru_version1ServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createAccount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateAccountInterceptors() -> [ServerInterceptor<Haru_AccountRequest, Haru_AccountReply>]

  /// - Returns: Interceptors to use when handling 'getProfile'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetProfileInterceptors() -> [ServerInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when handling 'updateProfile'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateProfileInterceptors() -> [ServerInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when handling 'getPoint'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetPointInterceptors() -> [ServerInterceptor<Haru_PointRequest, Haru_PointReply>]

  /// - Returns: Interceptors to use when handling 'incrPoint'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeIncrPointInterceptors() -> [ServerInterceptor<Haru_PointRequest, Haru_PointReply>]

  /// - Returns: Interceptors to use when handling 'getPlaceByID'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetPlaceByIDInterceptors() -> [ServerInterceptor<Haru_PlaceRequest, Haru_PlaceReply>]

  /// - Returns: Interceptors to use when handling 'getPlaceByInput'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetPlaceByInputInterceptors() -> [ServerInterceptor<Haru_PlaceRequest, Haru_PlaceReply>]

  /// - Returns: Interceptors to use when handling 'updatePlaceProfile'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdatePlaceProfileInterceptors() -> [ServerInterceptor<Haru_PlaceRequest, Haru_PlaceProfileReply>]

  /// - Returns: Interceptors to use when handling 'getPlaceProfile'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetPlaceProfileInterceptors() -> [ServerInterceptor<Haru_PlaceRequest, Haru_PlaceProfileReply>]

  /// - Returns: Interceptors to use when handling 'getNearbySearch'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetNearbySearchInterceptors() -> [ServerInterceptor<Haru_PlaceRequest, Haru_PlaceReplyList>]
}

internal enum Haru_version1ServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "version1",
    fullName: "haru.version1",
    methods: [
      Haru_version1ServerMetadata.Methods.createAccount,
      Haru_version1ServerMetadata.Methods.getProfile,
      Haru_version1ServerMetadata.Methods.updateProfile,
      Haru_version1ServerMetadata.Methods.getPoint,
      Haru_version1ServerMetadata.Methods.incrPoint,
      Haru_version1ServerMetadata.Methods.getPlaceByID,
      Haru_version1ServerMetadata.Methods.getPlaceByInput,
      Haru_version1ServerMetadata.Methods.updatePlaceProfile,
      Haru_version1ServerMetadata.Methods.getPlaceProfile,
      Haru_version1ServerMetadata.Methods.getNearbySearch,
    ]
  )

  internal enum Methods {
    internal static let createAccount = GRPCMethodDescriptor(
      name: "CreateAccount",
      path: "/haru.version1/CreateAccount",
      type: GRPCCallType.unary
    )

    internal static let getProfile = GRPCMethodDescriptor(
      name: "GetProfile",
      path: "/haru.version1/GetProfile",
      type: GRPCCallType.unary
    )

    internal static let updateProfile = GRPCMethodDescriptor(
      name: "UpdateProfile",
      path: "/haru.version1/UpdateProfile",
      type: GRPCCallType.unary
    )

    internal static let getPoint = GRPCMethodDescriptor(
      name: "GetPoint",
      path: "/haru.version1/GetPoint",
      type: GRPCCallType.unary
    )

    internal static let incrPoint = GRPCMethodDescriptor(
      name: "IncrPoint",
      path: "/haru.version1/IncrPoint",
      type: GRPCCallType.unary
    )

    internal static let getPlaceByID = GRPCMethodDescriptor(
      name: "GetPlaceByID",
      path: "/haru.version1/GetPlaceByID",
      type: GRPCCallType.unary
    )

    internal static let getPlaceByInput = GRPCMethodDescriptor(
      name: "GetPlaceByInput",
      path: "/haru.version1/GetPlaceByInput",
      type: GRPCCallType.unary
    )

    internal static let updatePlaceProfile = GRPCMethodDescriptor(
      name: "UpdatePlaceProfile",
      path: "/haru.version1/UpdatePlaceProfile",
      type: GRPCCallType.unary
    )

    internal static let getPlaceProfile = GRPCMethodDescriptor(
      name: "GetPlaceProfile",
      path: "/haru.version1/GetPlaceProfile",
      type: GRPCCallType.unary
    )

    internal static let getNearbySearch = GRPCMethodDescriptor(
      name: "GetNearbySearch",
      path: "/haru.version1/GetNearbySearch",
      type: GRPCCallType.unary
    )
  }
}
