// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto/haru.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Haru_AccountRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 = 0

  var registerTimestamp: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Haru_AccountReply {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 = 0

  var registerTimestamp: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Haru_ProfileRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var profile: Haru_Profile {
    get {return _profile ?? Haru_Profile()}
    set {_profile = newValue}
  }
  /// Returns true if `profile` has been explicitly set.
  var hasProfile: Bool {return self._profile != nil}
  /// Clears the value of `profile`. Subsequent reads from it will return its default value.
  mutating func clearProfile() {self._profile = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _profile: Haru_Profile? = nil
}

struct Haru_ProfileReply {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var profile: Haru_Profile {
    get {return _profile ?? Haru_Profile()}
    set {_profile = newValue}
  }
  /// Returns true if `profile` has been explicitly set.
  var hasProfile: Bool {return self._profile != nil}
  /// Clears the value of `profile`. Subsequent reads from it will return its default value.
  mutating func clearProfile() {self._profile = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _profile: Haru_Profile? = nil
}

struct Haru_JoinRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var join: Haru_Join {
    get {return _join ?? Haru_Join()}
    set {_join = newValue}
  }
  /// Returns true if `join` has been explicitly set.
  var hasJoin: Bool {return self._join != nil}
  /// Clears the value of `join`. Subsequent reads from it will return its default value.
  mutating func clearJoin() {self._join = nil}

  var profile: Haru_Profile {
    get {return _profile ?? Haru_Profile()}
    set {_profile = newValue}
  }
  /// Returns true if `profile` has been explicitly set.
  var hasProfile: Bool {return self._profile != nil}
  /// Clears the value of `profile`. Subsequent reads from it will return its default value.
  mutating func clearProfile() {self._profile = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _join: Haru_Join? = nil
  fileprivate var _profile: Haru_Profile? = nil
}

struct Haru_JoinReply {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var join: Haru_Join {
    get {return _join ?? Haru_Join()}
    set {_join = newValue}
  }
  /// Returns true if `join` has been explicitly set.
  var hasJoin: Bool {return self._join != nil}
  /// Clears the value of `join`. Subsequent reads from it will return its default value.
  mutating func clearJoin() {self._join = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _join: Haru_Join? = nil
}

struct Haru_Profile {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 = 0

  var nickname: String = String()

  var age: Int64 = 0

  var sex: Int64 = 0

  var gross: Int64 = 0

  var years: Int64 = 0

  var rounds: [Int64] = []

  var desc: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Haru_RoundRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var round: Haru_Round {
    get {return _round ?? Haru_Round()}
    set {_round = newValue}
  }
  /// Returns true if `round` has been explicitly set.
  var hasRound: Bool {return self._round != nil}
  /// Clears the value of `round`. Subsequent reads from it will return its default value.
  mutating func clearRound() {self._round = nil}

  var place: Haru_Place {
    get {return _place ?? Haru_Place()}
    set {_place = newValue}
  }
  /// Returns true if `place` has been explicitly set.
  var hasPlace: Bool {return self._place != nil}
  /// Clears the value of `place`. Subsequent reads from it will return its default value.
  mutating func clearPlace() {self._place = nil}

  var join: Haru_Join {
    get {return _join ?? Haru_Join()}
    set {_join = newValue}
  }
  /// Returns true if `join` has been explicitly set.
  var hasJoin: Bool {return self._join != nil}
  /// Clears the value of `join`. Subsequent reads from it will return its default value.
  mutating func clearJoin() {self._join = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _round: Haru_Round? = nil
  fileprivate var _place: Haru_Place? = nil
  fileprivate var _join: Haru_Join? = nil
}

struct Haru_RoundReply {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var round: Haru_Round {
    get {return _round ?? Haru_Round()}
    set {_round = newValue}
  }
  /// Returns true if `round` has been explicitly set.
  var hasRound: Bool {return self._round != nil}
  /// Clears the value of `round`. Subsequent reads from it will return its default value.
  mutating func clearRound() {self._round = nil}

  var place: Haru_Place {
    get {return _place ?? Haru_Place()}
    set {_place = newValue}
  }
  /// Returns true if `place` has been explicitly set.
  var hasPlace: Bool {return self._place != nil}
  /// Clears the value of `place`. Subsequent reads from it will return its default value.
  mutating func clearPlace() {self._place = nil}

  var join: Haru_Join {
    get {return _join ?? Haru_Join()}
    set {_join = newValue}
  }
  /// Returns true if `join` has been explicitly set.
  var hasJoin: Bool {return self._join != nil}
  /// Clears the value of `join`. Subsequent reads from it will return its default value.
  mutating func clearJoin() {self._join = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _round: Haru_Round? = nil
  fileprivate var _place: Haru_Place? = nil
  fileprivate var _join: Haru_Join? = nil
}

struct Haru_Round {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var host: Int64 {
    get {return _storage._host}
    set {_uniqueStorage()._host = newValue}
  }

  var time: Int64 {
    get {return _storage._time}
    set {_uniqueStorage()._time = newValue}
  }

  var price: Int64 {
    get {return _storage._price}
    set {_uniqueStorage()._price = newValue}
  }

  /// type 으로 상황별 구분해서 사용 ex ) 0 : 필드 18홀, 1 : 필드 9홀, 2 : 스크린 9홀 ...
  var typePlay: Int64 {
    get {return _storage._typePlay}
    set {_uniqueStorage()._typePlay = newValue}
  }

  var typeAge: Int64 {
    get {return _storage._typeAge}
    set {_uniqueStorage()._typeAge = newValue}
  }

  var typeSex: Int64 {
    get {return _storage._typeSex}
    set {_uniqueStorage()._typeSex = newValue}
  }

  var typeScoreOfGross: Int64 {
    get {return _storage._typeScoreOfGross}
    set {_uniqueStorage()._typeScoreOfGross = newValue}
  }

  var typeExperienceOfYears: Int64 {
    get {return _storage._typeExperienceOfYears}
    set {_uniqueStorage()._typeExperienceOfYears = newValue}
  }

  var placeID: String {
    get {return _storage._placeID}
    set {_uniqueStorage()._placeID = newValue}
  }

  var placeName: String {
    get {return _storage._placeName}
    set {_uniqueStorage()._placeName = newValue}
  }

  var placeAddress: String {
    get {return _storage._placeAddress}
    set {_uniqueStorage()._placeAddress = newValue}
  }

  /// 탐색용 키
  var shortAddress: String {
    get {return _storage._shortAddress}
    set {_uniqueStorage()._shortAddress = newValue}
  }

  var lat: String {
    get {return _storage._lat}
    set {_uniqueStorage()._lat = newValue}
  }

  var long: String {
    get {return _storage._long}
    set {_uniqueStorage()._long = newValue}
  }

  var updated: Int64 {
    get {return _storage._updated}
    set {_uniqueStorage()._updated = newValue}
  }

  var placeImg: String {
    get {return _storage._placeImg}
    set {_uniqueStorage()._placeImg = newValue}
  }

  var typeHole: Int64 {
    get {return _storage._typeHole}
    set {_uniqueStorage()._typeHole = newValue}
  }

  var personFull: Int64 {
    get {return _storage._personFull}
    set {_uniqueStorage()._personFull = newValue}
  }

  var person: Int64 {
    get {return _storage._person}
    set {_uniqueStorage()._person = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct Haru_Place {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 = 0

  var name: String = String()

  var location: String = String()

  var lat: String = String()

  var long: String = String()

  var photo: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Haru_Join {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// roundID
  var id: Int64 = 0

  var userID: Int64 = 0

  var ids: [Int64] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Haru_Review {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int64 = 0

  var ids: [Int64] = []

  var reviews: [String] = []

  var updated: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Haru_FilterdRoundsRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var isInit: Bool = false

  var timeMin: Int64 = 0

  var timeMax: Int64 = 0

  var page: Int64 = 0

  var typePlay: Int64 = 0

  var typeAge: Int64 = 0

  var typeSex: Int64 = 0

  var typeScoreOfGross: Int64 = 0

  var typeExperienceOfYears: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Haru_FilterdRoundsReply {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var rounds: [Haru_Round] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Haru_AccountRequest: @unchecked Sendable {}
extension Haru_AccountReply: @unchecked Sendable {}
extension Haru_ProfileRequest: @unchecked Sendable {}
extension Haru_ProfileReply: @unchecked Sendable {}
extension Haru_JoinRequest: @unchecked Sendable {}
extension Haru_JoinReply: @unchecked Sendable {}
extension Haru_Profile: @unchecked Sendable {}
extension Haru_RoundRequest: @unchecked Sendable {}
extension Haru_RoundReply: @unchecked Sendable {}
extension Haru_Round: @unchecked Sendable {}
extension Haru_Place: @unchecked Sendable {}
extension Haru_Join: @unchecked Sendable {}
extension Haru_Review: @unchecked Sendable {}
extension Haru_FilterdRoundsRequest: @unchecked Sendable {}
extension Haru_FilterdRoundsReply: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "haru"

extension Haru_AccountRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AccountRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "register_timestamp"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.registerTimestamp) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.registerTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.registerTimestamp, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_AccountRequest, rhs: Haru_AccountRequest) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.registerTimestamp != rhs.registerTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_AccountReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".AccountReply"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "register_timestamp"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.registerTimestamp) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.registerTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.registerTimestamp, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_AccountReply, rhs: Haru_AccountReply) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.registerTimestamp != rhs.registerTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_ProfileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProfileRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "profile"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._profile) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._profile {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_ProfileRequest, rhs: Haru_ProfileRequest) -> Bool {
    if lhs._profile != rhs._profile {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_ProfileReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ProfileReply"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "profile"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._profile) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._profile {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_ProfileReply, rhs: Haru_ProfileReply) -> Bool {
    if lhs._profile != rhs._profile {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_JoinRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".JoinRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "join"),
    2: .same(proto: "profile"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._join) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._profile) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._join {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._profile {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_JoinRequest, rhs: Haru_JoinRequest) -> Bool {
    if lhs._join != rhs._join {return false}
    if lhs._profile != rhs._profile {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_JoinReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".JoinReply"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "join"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._join) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._join {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_JoinReply, rhs: Haru_JoinReply) -> Bool {
    if lhs._join != rhs._join {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_Profile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Profile"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "nickname"),
    3: .same(proto: "age"),
    4: .same(proto: "sex"),
    5: .same(proto: "gross"),
    6: .same(proto: "years"),
    7: .same(proto: "rounds"),
    8: .same(proto: "desc"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.nickname) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.age) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.sex) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.gross) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.years) }()
      case 7: try { try decoder.decodeRepeatedInt64Field(value: &self.rounds) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.desc) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.nickname.isEmpty {
      try visitor.visitSingularStringField(value: self.nickname, fieldNumber: 2)
    }
    if self.age != 0 {
      try visitor.visitSingularInt64Field(value: self.age, fieldNumber: 3)
    }
    if self.sex != 0 {
      try visitor.visitSingularInt64Field(value: self.sex, fieldNumber: 4)
    }
    if self.gross != 0 {
      try visitor.visitSingularInt64Field(value: self.gross, fieldNumber: 5)
    }
    if self.years != 0 {
      try visitor.visitSingularInt64Field(value: self.years, fieldNumber: 6)
    }
    if !self.rounds.isEmpty {
      try visitor.visitPackedInt64Field(value: self.rounds, fieldNumber: 7)
    }
    if !self.desc.isEmpty {
      try visitor.visitSingularStringField(value: self.desc, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_Profile, rhs: Haru_Profile) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.nickname != rhs.nickname {return false}
    if lhs.age != rhs.age {return false}
    if lhs.sex != rhs.sex {return false}
    if lhs.gross != rhs.gross {return false}
    if lhs.years != rhs.years {return false}
    if lhs.rounds != rhs.rounds {return false}
    if lhs.desc != rhs.desc {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_RoundRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RoundRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "round"),
    2: .same(proto: "place"),
    3: .same(proto: "join"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._round) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._place) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._join) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._round {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._place {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._join {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_RoundRequest, rhs: Haru_RoundRequest) -> Bool {
    if lhs._round != rhs._round {return false}
    if lhs._place != rhs._place {return false}
    if lhs._join != rhs._join {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_RoundReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RoundReply"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "round"),
    2: .same(proto: "place"),
    3: .same(proto: "join"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._round) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._place) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._join) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._round {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._place {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._join {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_RoundReply, rhs: Haru_RoundReply) -> Bool {
    if lhs._round != rhs._round {return false}
    if lhs._place != rhs._place {return false}
    if lhs._join != rhs._join {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_Round: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Round"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "host"),
    3: .same(proto: "time"),
    4: .same(proto: "price"),
    5: .standard(proto: "type_play"),
    6: .standard(proto: "type_age"),
    7: .standard(proto: "type_sex"),
    8: .standard(proto: "type_score_of_gross"),
    9: .standard(proto: "type_experience_of_years"),
    10: .standard(proto: "place_id"),
    11: .standard(proto: "place_name"),
    12: .standard(proto: "place_address"),
    13: .standard(proto: "short_address"),
    14: .same(proto: "lat"),
    15: .same(proto: "long"),
    16: .same(proto: "updated"),
    17: .standard(proto: "place_img"),
    18: .standard(proto: "type_hole"),
    19: .standard(proto: "person_full"),
    20: .same(proto: "person"),
  ]

  fileprivate class _StorageClass {
    var _id: Int64 = 0
    var _host: Int64 = 0
    var _time: Int64 = 0
    var _price: Int64 = 0
    var _typePlay: Int64 = 0
    var _typeAge: Int64 = 0
    var _typeSex: Int64 = 0
    var _typeScoreOfGross: Int64 = 0
    var _typeExperienceOfYears: Int64 = 0
    var _placeID: String = String()
    var _placeName: String = String()
    var _placeAddress: String = String()
    var _shortAddress: String = String()
    var _lat: String = String()
    var _long: String = String()
    var _updated: Int64 = 0
    var _placeImg: String = String()
    var _typeHole: Int64 = 0
    var _personFull: Int64 = 0
    var _person: Int64 = 0

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _host = source._host
      _time = source._time
      _price = source._price
      _typePlay = source._typePlay
      _typeAge = source._typeAge
      _typeSex = source._typeSex
      _typeScoreOfGross = source._typeScoreOfGross
      _typeExperienceOfYears = source._typeExperienceOfYears
      _placeID = source._placeID
      _placeName = source._placeName
      _placeAddress = source._placeAddress
      _shortAddress = source._shortAddress
      _lat = source._lat
      _long = source._long
      _updated = source._updated
      _placeImg = source._placeImg
      _typeHole = source._typeHole
      _personFull = source._personFull
      _person = source._person
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt64Field(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._host) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._time) }()
        case 4: try { try decoder.decodeSingularInt64Field(value: &_storage._price) }()
        case 5: try { try decoder.decodeSingularInt64Field(value: &_storage._typePlay) }()
        case 6: try { try decoder.decodeSingularInt64Field(value: &_storage._typeAge) }()
        case 7: try { try decoder.decodeSingularInt64Field(value: &_storage._typeSex) }()
        case 8: try { try decoder.decodeSingularInt64Field(value: &_storage._typeScoreOfGross) }()
        case 9: try { try decoder.decodeSingularInt64Field(value: &_storage._typeExperienceOfYears) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._placeID) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._placeName) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._placeAddress) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._shortAddress) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._lat) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._long) }()
        case 16: try { try decoder.decodeSingularInt64Field(value: &_storage._updated) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._placeImg) }()
        case 18: try { try decoder.decodeSingularInt64Field(value: &_storage._typeHole) }()
        case 19: try { try decoder.decodeSingularInt64Field(value: &_storage._personFull) }()
        case 20: try { try decoder.decodeSingularInt64Field(value: &_storage._person) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._id != 0 {
        try visitor.visitSingularInt64Field(value: _storage._id, fieldNumber: 1)
      }
      if _storage._host != 0 {
        try visitor.visitSingularInt64Field(value: _storage._host, fieldNumber: 2)
      }
      if _storage._time != 0 {
        try visitor.visitSingularInt64Field(value: _storage._time, fieldNumber: 3)
      }
      if _storage._price != 0 {
        try visitor.visitSingularInt64Field(value: _storage._price, fieldNumber: 4)
      }
      if _storage._typePlay != 0 {
        try visitor.visitSingularInt64Field(value: _storage._typePlay, fieldNumber: 5)
      }
      if _storage._typeAge != 0 {
        try visitor.visitSingularInt64Field(value: _storage._typeAge, fieldNumber: 6)
      }
      if _storage._typeSex != 0 {
        try visitor.visitSingularInt64Field(value: _storage._typeSex, fieldNumber: 7)
      }
      if _storage._typeScoreOfGross != 0 {
        try visitor.visitSingularInt64Field(value: _storage._typeScoreOfGross, fieldNumber: 8)
      }
      if _storage._typeExperienceOfYears != 0 {
        try visitor.visitSingularInt64Field(value: _storage._typeExperienceOfYears, fieldNumber: 9)
      }
      if !_storage._placeID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._placeID, fieldNumber: 10)
      }
      if !_storage._placeName.isEmpty {
        try visitor.visitSingularStringField(value: _storage._placeName, fieldNumber: 11)
      }
      if !_storage._placeAddress.isEmpty {
        try visitor.visitSingularStringField(value: _storage._placeAddress, fieldNumber: 12)
      }
      if !_storage._shortAddress.isEmpty {
        try visitor.visitSingularStringField(value: _storage._shortAddress, fieldNumber: 13)
      }
      if !_storage._lat.isEmpty {
        try visitor.visitSingularStringField(value: _storage._lat, fieldNumber: 14)
      }
      if !_storage._long.isEmpty {
        try visitor.visitSingularStringField(value: _storage._long, fieldNumber: 15)
      }
      if _storage._updated != 0 {
        try visitor.visitSingularInt64Field(value: _storage._updated, fieldNumber: 16)
      }
      if !_storage._placeImg.isEmpty {
        try visitor.visitSingularStringField(value: _storage._placeImg, fieldNumber: 17)
      }
      if _storage._typeHole != 0 {
        try visitor.visitSingularInt64Field(value: _storage._typeHole, fieldNumber: 18)
      }
      if _storage._personFull != 0 {
        try visitor.visitSingularInt64Field(value: _storage._personFull, fieldNumber: 19)
      }
      if _storage._person != 0 {
        try visitor.visitSingularInt64Field(value: _storage._person, fieldNumber: 20)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_Round, rhs: Haru_Round) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._host != rhs_storage._host {return false}
        if _storage._time != rhs_storage._time {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._typePlay != rhs_storage._typePlay {return false}
        if _storage._typeAge != rhs_storage._typeAge {return false}
        if _storage._typeSex != rhs_storage._typeSex {return false}
        if _storage._typeScoreOfGross != rhs_storage._typeScoreOfGross {return false}
        if _storage._typeExperienceOfYears != rhs_storage._typeExperienceOfYears {return false}
        if _storage._placeID != rhs_storage._placeID {return false}
        if _storage._placeName != rhs_storage._placeName {return false}
        if _storage._placeAddress != rhs_storage._placeAddress {return false}
        if _storage._shortAddress != rhs_storage._shortAddress {return false}
        if _storage._lat != rhs_storage._lat {return false}
        if _storage._long != rhs_storage._long {return false}
        if _storage._updated != rhs_storage._updated {return false}
        if _storage._placeImg != rhs_storage._placeImg {return false}
        if _storage._typeHole != rhs_storage._typeHole {return false}
        if _storage._personFull != rhs_storage._personFull {return false}
        if _storage._person != rhs_storage._person {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_Place: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Place"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "name"),
    3: .same(proto: "location"),
    4: .same(proto: "lat"),
    5: .same(proto: "long"),
    6: .same(proto: "photo"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.location) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.lat) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.long) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.photo) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 2)
    }
    if !self.location.isEmpty {
      try visitor.visitSingularStringField(value: self.location, fieldNumber: 3)
    }
    if !self.lat.isEmpty {
      try visitor.visitSingularStringField(value: self.lat, fieldNumber: 4)
    }
    if !self.long.isEmpty {
      try visitor.visitSingularStringField(value: self.long, fieldNumber: 5)
    }
    if !self.photo.isEmpty {
      try visitor.visitSingularStringField(value: self.photo, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_Place, rhs: Haru_Place) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.name != rhs.name {return false}
    if lhs.location != rhs.location {return false}
    if lhs.lat != rhs.lat {return false}
    if lhs.long != rhs.long {return false}
    if lhs.photo != rhs.photo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_Join: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Join"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "user_id"),
    3: .same(proto: "ids"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.userID) }()
      case 3: try { try decoder.decodeRepeatedInt64Field(value: &self.ids) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if self.userID != 0 {
      try visitor.visitSingularInt64Field(value: self.userID, fieldNumber: 2)
    }
    if !self.ids.isEmpty {
      try visitor.visitPackedInt64Field(value: self.ids, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_Join, rhs: Haru_Join) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_Review: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Review"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "ids"),
    3: .same(proto: "reviews"),
    4: .same(proto: "updated"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.id) }()
      case 2: try { try decoder.decodeRepeatedInt64Field(value: &self.ids) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.reviews) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.updated) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.id != 0 {
      try visitor.visitSingularInt64Field(value: self.id, fieldNumber: 1)
    }
    if !self.ids.isEmpty {
      try visitor.visitPackedInt64Field(value: self.ids, fieldNumber: 2)
    }
    if !self.reviews.isEmpty {
      try visitor.visitRepeatedStringField(value: self.reviews, fieldNumber: 3)
    }
    if self.updated != 0 {
      try visitor.visitSingularInt64Field(value: self.updated, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_Review, rhs: Haru_Review) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.ids != rhs.ids {return false}
    if lhs.reviews != rhs.reviews {return false}
    if lhs.updated != rhs.updated {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_FilterdRoundsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FilterdRoundsRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "is_init"),
    2: .standard(proto: "time_min"),
    3: .standard(proto: "time_max"),
    4: .same(proto: "page"),
    5: .standard(proto: "type_play"),
    6: .standard(proto: "type_age"),
    7: .standard(proto: "type_sex"),
    8: .standard(proto: "type_score_of_gross"),
    9: .standard(proto: "type_experience_of_years"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isInit) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.timeMin) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.timeMax) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.page) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.typePlay) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.typeAge) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.typeSex) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.typeScoreOfGross) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.typeExperienceOfYears) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isInit != false {
      try visitor.visitSingularBoolField(value: self.isInit, fieldNumber: 1)
    }
    if self.timeMin != 0 {
      try visitor.visitSingularInt64Field(value: self.timeMin, fieldNumber: 2)
    }
    if self.timeMax != 0 {
      try visitor.visitSingularInt64Field(value: self.timeMax, fieldNumber: 3)
    }
    if self.page != 0 {
      try visitor.visitSingularInt64Field(value: self.page, fieldNumber: 4)
    }
    if self.typePlay != 0 {
      try visitor.visitSingularInt64Field(value: self.typePlay, fieldNumber: 5)
    }
    if self.typeAge != 0 {
      try visitor.visitSingularInt64Field(value: self.typeAge, fieldNumber: 6)
    }
    if self.typeSex != 0 {
      try visitor.visitSingularInt64Field(value: self.typeSex, fieldNumber: 7)
    }
    if self.typeScoreOfGross != 0 {
      try visitor.visitSingularInt64Field(value: self.typeScoreOfGross, fieldNumber: 8)
    }
    if self.typeExperienceOfYears != 0 {
      try visitor.visitSingularInt64Field(value: self.typeExperienceOfYears, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_FilterdRoundsRequest, rhs: Haru_FilterdRoundsRequest) -> Bool {
    if lhs.isInit != rhs.isInit {return false}
    if lhs.timeMin != rhs.timeMin {return false}
    if lhs.timeMax != rhs.timeMax {return false}
    if lhs.page != rhs.page {return false}
    if lhs.typePlay != rhs.typePlay {return false}
    if lhs.typeAge != rhs.typeAge {return false}
    if lhs.typeSex != rhs.typeSex {return false}
    if lhs.typeScoreOfGross != rhs.typeScoreOfGross {return false}
    if lhs.typeExperienceOfYears != rhs.typeExperienceOfYears {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Haru_FilterdRoundsReply: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FilterdRoundsReply"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "Rounds"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.rounds) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.rounds.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.rounds, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Haru_FilterdRoundsReply, rhs: Haru_FilterdRoundsReply) -> Bool {
    if lhs.rounds != rhs.rounds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
