//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: proto/haru.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Service definition.
///
/// Usage: instantiate `Haru_version1Client`, then call methods of this protocol to make API calls.
internal protocol Haru_version1ClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Haru_version1ClientInterceptorFactoryProtocol? { get }

  func createAccount(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_AccountRequest, Haru_AccountReply>

  func getProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func updateProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func createGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_GameRequest, Haru_GameReply>

  func updateGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_GameRequest, Haru_GameReply>

  func getGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_GameRequest, Haru_GameReply>

  func getFilterdGames(
    _ request: Haru_FilterdGamesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_FilterdGamesRequest, Haru_FilterdGamesReply>

  func join(
    _ request: Haru_JoinRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Haru_JoinRequest, Haru_JoinReply>
}

extension Haru_version1ClientProtocol {
  internal var serviceName: String {
    return "haru.version1"
  }

  /// Unary call to CreateAccount
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateAccount.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createAccount(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_AccountRequest, Haru_AccountReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  /// Unary call to GetProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to GetProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }

  /// Unary call to UpdateProfile
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateProfile.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? []
    )
  }

  /// Unary call to CreateGame
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateGame.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func createGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_GameRequest, Haru_GameReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateGameInterceptors() ?? []
    )
  }

  /// Unary call to UpdateGame
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateGame.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func updateGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_GameRequest, Haru_GameReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateGameInterceptors() ?? []
    )
  }

  /// Unary call to GetGame
  ///
  /// - Parameters:
  ///   - request: Request to send to GetGame.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_GameRequest, Haru_GameReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetGameInterceptors() ?? []
    )
  }

  /// Unary call to GetFilterdGames
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFilterdGames.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getFilterdGames(
    _ request: Haru_FilterdGamesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_FilterdGamesRequest, Haru_FilterdGamesReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getFilterdGames.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFilterdGamesInterceptors() ?? []
    )
  }

  /// Unary call to Join
  ///
  /// - Parameters:
  ///   - request: Request to send to Join.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func join(
    _ request: Haru_JoinRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Haru_JoinRequest, Haru_JoinReply> {
    return self.makeUnaryCall(
      path: Haru_version1ClientMetadata.Methods.join.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeJoinInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Haru_version1Client: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Haru_version1NIOClient")
internal final class Haru_version1Client: Haru_version1ClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Haru_version1ClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the haru.version1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Haru_version1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Haru_version1NIOClient: Haru_version1ClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol?

  /// Creates a client for the haru.version1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Haru_version1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
/// Service definition.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Haru_version1AsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Haru_version1ClientInterceptorFactoryProtocol? { get }

  func makeCreateAccountCall(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_AccountRequest, Haru_AccountReply>

  func makeGetProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func makeUpdateProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply>

  func makeCreateGameCall(
    _ request: Haru_GameRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_GameRequest, Haru_GameReply>

  func makeUpdateGameCall(
    _ request: Haru_GameRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_GameRequest, Haru_GameReply>

  func makeGetGameCall(
    _ request: Haru_GameRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_GameRequest, Haru_GameReply>

  func makeGetFilterdGamesCall(
    _ request: Haru_FilterdGamesRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_FilterdGamesRequest, Haru_FilterdGamesReply>

  func makeJoinCall(
    _ request: Haru_JoinRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Haru_JoinRequest, Haru_JoinReply>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Haru_version1AsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Haru_version1ClientMetadata.serviceDescriptor
  }

  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeCreateAccountCall(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_AccountRequest, Haru_AccountReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  internal func makeGetProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }

  internal func makeUpdateProfileCall(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_ProfileRequest, Haru_ProfileReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? []
    )
  }

  internal func makeCreateGameCall(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_GameRequest, Haru_GameReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateGameInterceptors() ?? []
    )
  }

  internal func makeUpdateGameCall(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_GameRequest, Haru_GameReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateGameInterceptors() ?? []
    )
  }

  internal func makeGetGameCall(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_GameRequest, Haru_GameReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetGameInterceptors() ?? []
    )
  }

  internal func makeGetFilterdGamesCall(
    _ request: Haru_FilterdGamesRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_FilterdGamesRequest, Haru_FilterdGamesReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getFilterdGames.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFilterdGamesInterceptors() ?? []
    )
  }

  internal func makeJoinCall(
    _ request: Haru_JoinRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Haru_JoinRequest, Haru_JoinReply> {
    return self.makeAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.join.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeJoinInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Haru_version1AsyncClientProtocol {
  internal func createAccount(
    _ request: Haru_AccountRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_AccountReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createAccount.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? []
    )
  }

  internal func getProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_ProfileReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetProfileInterceptors() ?? []
    )
  }

  internal func updateProfile(
    _ request: Haru_ProfileRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_ProfileReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateProfile.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? []
    )
  }

  internal func createGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_GameReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.createGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateGameInterceptors() ?? []
    )
  }

  internal func updateGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_GameReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.updateGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateGameInterceptors() ?? []
    )
  }

  internal func getGame(
    _ request: Haru_GameRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_GameReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getGame.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetGameInterceptors() ?? []
    )
  }

  internal func getFilterdGames(
    _ request: Haru_FilterdGamesRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_FilterdGamesReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.getFilterdGames.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFilterdGamesInterceptors() ?? []
    )
  }

  internal func join(
    _ request: Haru_JoinRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Haru_JoinReply {
    return try await self.performAsyncUnaryCall(
      path: Haru_version1ClientMetadata.Methods.join.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeJoinInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Haru_version1AsyncClient: Haru_version1AsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Haru_version1ClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Haru_version1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Haru_version1ClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'createAccount'.
  func makeCreateAccountInterceptors() -> [ClientInterceptor<Haru_AccountRequest, Haru_AccountReply>]

  /// - Returns: Interceptors to use when invoking 'getProfile'.
  func makeGetProfileInterceptors() -> [ClientInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when invoking 'updateProfile'.
  func makeUpdateProfileInterceptors() -> [ClientInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when invoking 'createGame'.
  func makeCreateGameInterceptors() -> [ClientInterceptor<Haru_GameRequest, Haru_GameReply>]

  /// - Returns: Interceptors to use when invoking 'updateGame'.
  func makeUpdateGameInterceptors() -> [ClientInterceptor<Haru_GameRequest, Haru_GameReply>]

  /// - Returns: Interceptors to use when invoking 'getGame'.
  func makeGetGameInterceptors() -> [ClientInterceptor<Haru_GameRequest, Haru_GameReply>]

  /// - Returns: Interceptors to use when invoking 'getFilterdGames'.
  func makeGetFilterdGamesInterceptors() -> [ClientInterceptor<Haru_FilterdGamesRequest, Haru_FilterdGamesReply>]

  /// - Returns: Interceptors to use when invoking 'join'.
  func makeJoinInterceptors() -> [ClientInterceptor<Haru_JoinRequest, Haru_JoinReply>]
}

internal enum Haru_version1ClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "version1",
    fullName: "haru.version1",
    methods: [
      Haru_version1ClientMetadata.Methods.createAccount,
      Haru_version1ClientMetadata.Methods.getProfile,
      Haru_version1ClientMetadata.Methods.updateProfile,
      Haru_version1ClientMetadata.Methods.createGame,
      Haru_version1ClientMetadata.Methods.updateGame,
      Haru_version1ClientMetadata.Methods.getGame,
      Haru_version1ClientMetadata.Methods.getFilterdGames,
      Haru_version1ClientMetadata.Methods.join,
    ]
  )

  internal enum Methods {
    internal static let createAccount = GRPCMethodDescriptor(
      name: "CreateAccount",
      path: "/haru.version1/CreateAccount",
      type: GRPCCallType.unary
    )

    internal static let getProfile = GRPCMethodDescriptor(
      name: "GetProfile",
      path: "/haru.version1/GetProfile",
      type: GRPCCallType.unary
    )

    internal static let updateProfile = GRPCMethodDescriptor(
      name: "UpdateProfile",
      path: "/haru.version1/UpdateProfile",
      type: GRPCCallType.unary
    )

    internal static let createGame = GRPCMethodDescriptor(
      name: "CreateGame",
      path: "/haru.version1/CreateGame",
      type: GRPCCallType.unary
    )

    internal static let updateGame = GRPCMethodDescriptor(
      name: "UpdateGame",
      path: "/haru.version1/UpdateGame",
      type: GRPCCallType.unary
    )

    internal static let getGame = GRPCMethodDescriptor(
      name: "GetGame",
      path: "/haru.version1/GetGame",
      type: GRPCCallType.unary
    )

    internal static let getFilterdGames = GRPCMethodDescriptor(
      name: "GetFilterdGames",
      path: "/haru.version1/GetFilterdGames",
      type: GRPCCallType.unary
    )

    internal static let join = GRPCMethodDescriptor(
      name: "Join",
      path: "/haru.version1/Join",
      type: GRPCCallType.unary
    )
  }
}

/// Service definition.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Haru_version1Provider: CallHandlerProvider {
  var interceptors: Haru_version1ServerInterceptorFactoryProtocol? { get }

  func createAccount(request: Haru_AccountRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_AccountReply>

  func getProfile(request: Haru_ProfileRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_ProfileReply>

  func updateProfile(request: Haru_ProfileRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_ProfileReply>

  func createGame(request: Haru_GameRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_GameReply>

  func updateGame(request: Haru_GameRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_GameReply>

  func getGame(request: Haru_GameRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_GameReply>

  func getFilterdGames(request: Haru_FilterdGamesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_FilterdGamesReply>

  func join(request: Haru_JoinRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Haru_JoinReply>
}

extension Haru_version1Provider {
  internal var serviceName: Substring {
    return Haru_version1ServerMetadata.serviceDescriptor.fullName[...]
  }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateAccount":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_AccountRequest>(),
        responseSerializer: ProtobufSerializer<Haru_AccountReply>(),
        interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? [],
        userFunction: self.createAccount(request:context:)
      )

    case "GetProfile":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeGetProfileInterceptors() ?? [],
        userFunction: self.getProfile(request:context:)
      )

    case "UpdateProfile":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? [],
        userFunction: self.updateProfile(request:context:)
      )

    case "CreateGame":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_GameRequest>(),
        responseSerializer: ProtobufSerializer<Haru_GameReply>(),
        interceptors: self.interceptors?.makeCreateGameInterceptors() ?? [],
        userFunction: self.createGame(request:context:)
      )

    case "UpdateGame":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_GameRequest>(),
        responseSerializer: ProtobufSerializer<Haru_GameReply>(),
        interceptors: self.interceptors?.makeUpdateGameInterceptors() ?? [],
        userFunction: self.updateGame(request:context:)
      )

    case "GetGame":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_GameRequest>(),
        responseSerializer: ProtobufSerializer<Haru_GameReply>(),
        interceptors: self.interceptors?.makeGetGameInterceptors() ?? [],
        userFunction: self.getGame(request:context:)
      )

    case "GetFilterdGames":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_FilterdGamesRequest>(),
        responseSerializer: ProtobufSerializer<Haru_FilterdGamesReply>(),
        interceptors: self.interceptors?.makeGetFilterdGamesInterceptors() ?? [],
        userFunction: self.getFilterdGames(request:context:)
      )

    case "Join":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_JoinRequest>(),
        responseSerializer: ProtobufSerializer<Haru_JoinReply>(),
        interceptors: self.interceptors?.makeJoinInterceptors() ?? [],
        userFunction: self.join(request:context:)
      )

    default:
      return nil
    }
  }
}

#if compiler(>=5.6)

/// Service definition.
///
/// To implement a server, implement an object which conforms to this protocol.
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Haru_version1AsyncProvider: CallHandlerProvider {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Haru_version1ServerInterceptorFactoryProtocol? { get }

  @Sendable func createAccount(
    request: Haru_AccountRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_AccountReply

  @Sendable func getProfile(
    request: Haru_ProfileRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_ProfileReply

  @Sendable func updateProfile(
    request: Haru_ProfileRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_ProfileReply

  @Sendable func createGame(
    request: Haru_GameRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_GameReply

  @Sendable func updateGame(
    request: Haru_GameRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_GameReply

  @Sendable func getGame(
    request: Haru_GameRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_GameReply

  @Sendable func getFilterdGames(
    request: Haru_FilterdGamesRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_FilterdGamesReply

  @Sendable func join(
    request: Haru_JoinRequest,
    context: GRPCAsyncServerCallContext
  ) async throws -> Haru_JoinReply
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Haru_version1AsyncProvider {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Haru_version1ServerMetadata.serviceDescriptor
  }

  internal var serviceName: Substring {
    return Haru_version1ServerMetadata.serviceDescriptor.fullName[...]
  }

  internal var interceptors: Haru_version1ServerInterceptorFactoryProtocol? {
    return nil
  }

  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CreateAccount":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_AccountRequest>(),
        responseSerializer: ProtobufSerializer<Haru_AccountReply>(),
        interceptors: self.interceptors?.makeCreateAccountInterceptors() ?? [],
        wrapping: self.createAccount(request:context:)
      )

    case "GetProfile":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeGetProfileInterceptors() ?? [],
        wrapping: self.getProfile(request:context:)
      )

    case "UpdateProfile":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_ProfileRequest>(),
        responseSerializer: ProtobufSerializer<Haru_ProfileReply>(),
        interceptors: self.interceptors?.makeUpdateProfileInterceptors() ?? [],
        wrapping: self.updateProfile(request:context:)
      )

    case "CreateGame":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_GameRequest>(),
        responseSerializer: ProtobufSerializer<Haru_GameReply>(),
        interceptors: self.interceptors?.makeCreateGameInterceptors() ?? [],
        wrapping: self.createGame(request:context:)
      )

    case "UpdateGame":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_GameRequest>(),
        responseSerializer: ProtobufSerializer<Haru_GameReply>(),
        interceptors: self.interceptors?.makeUpdateGameInterceptors() ?? [],
        wrapping: self.updateGame(request:context:)
      )

    case "GetGame":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_GameRequest>(),
        responseSerializer: ProtobufSerializer<Haru_GameReply>(),
        interceptors: self.interceptors?.makeGetGameInterceptors() ?? [],
        wrapping: self.getGame(request:context:)
      )

    case "GetFilterdGames":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_FilterdGamesRequest>(),
        responseSerializer: ProtobufSerializer<Haru_FilterdGamesReply>(),
        interceptors: self.interceptors?.makeGetFilterdGamesInterceptors() ?? [],
        wrapping: self.getFilterdGames(request:context:)
      )

    case "Join":
      return GRPCAsyncServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Haru_JoinRequest>(),
        responseSerializer: ProtobufSerializer<Haru_JoinReply>(),
        interceptors: self.interceptors?.makeJoinInterceptors() ?? [],
        wrapping: self.join(request:context:)
      )

    default:
      return nil
    }
  }
}

#endif // compiler(>=5.6)

internal protocol Haru_version1ServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'createAccount'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateAccountInterceptors() -> [ServerInterceptor<Haru_AccountRequest, Haru_AccountReply>]

  /// - Returns: Interceptors to use when handling 'getProfile'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetProfileInterceptors() -> [ServerInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when handling 'updateProfile'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateProfileInterceptors() -> [ServerInterceptor<Haru_ProfileRequest, Haru_ProfileReply>]

  /// - Returns: Interceptors to use when handling 'createGame'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateGameInterceptors() -> [ServerInterceptor<Haru_GameRequest, Haru_GameReply>]

  /// - Returns: Interceptors to use when handling 'updateGame'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateGameInterceptors() -> [ServerInterceptor<Haru_GameRequest, Haru_GameReply>]

  /// - Returns: Interceptors to use when handling 'getGame'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetGameInterceptors() -> [ServerInterceptor<Haru_GameRequest, Haru_GameReply>]

  /// - Returns: Interceptors to use when handling 'getFilterdGames'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetFilterdGamesInterceptors() -> [ServerInterceptor<Haru_FilterdGamesRequest, Haru_FilterdGamesReply>]

  /// - Returns: Interceptors to use when handling 'join'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeJoinInterceptors() -> [ServerInterceptor<Haru_JoinRequest, Haru_JoinReply>]
}

internal enum Haru_version1ServerMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "version1",
    fullName: "haru.version1",
    methods: [
      Haru_version1ServerMetadata.Methods.createAccount,
      Haru_version1ServerMetadata.Methods.getProfile,
      Haru_version1ServerMetadata.Methods.updateProfile,
      Haru_version1ServerMetadata.Methods.createGame,
      Haru_version1ServerMetadata.Methods.updateGame,
      Haru_version1ServerMetadata.Methods.getGame,
      Haru_version1ServerMetadata.Methods.getFilterdGames,
      Haru_version1ServerMetadata.Methods.join,
    ]
  )

  internal enum Methods {
    internal static let createAccount = GRPCMethodDescriptor(
      name: "CreateAccount",
      path: "/haru.version1/CreateAccount",
      type: GRPCCallType.unary
    )

    internal static let getProfile = GRPCMethodDescriptor(
      name: "GetProfile",
      path: "/haru.version1/GetProfile",
      type: GRPCCallType.unary
    )

    internal static let updateProfile = GRPCMethodDescriptor(
      name: "UpdateProfile",
      path: "/haru.version1/UpdateProfile",
      type: GRPCCallType.unary
    )

    internal static let createGame = GRPCMethodDescriptor(
      name: "CreateGame",
      path: "/haru.version1/CreateGame",
      type: GRPCCallType.unary
    )

    internal static let updateGame = GRPCMethodDescriptor(
      name: "UpdateGame",
      path: "/haru.version1/UpdateGame",
      type: GRPCCallType.unary
    )

    internal static let getGame = GRPCMethodDescriptor(
      name: "GetGame",
      path: "/haru.version1/GetGame",
      type: GRPCCallType.unary
    )

    internal static let getFilterdGames = GRPCMethodDescriptor(
      name: "GetFilterdGames",
      path: "/haru.version1/GetFilterdGames",
      type: GRPCCallType.unary
    )

    internal static let join = GRPCMethodDescriptor(
      name: "Join",
      path: "/haru.version1/Join",
      type: GRPCCallType.unary
    )
  }
}
