// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.3
// source: proto/haru.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RegisterTimestamp int64 `protobuf:"varint,2,opt,name=RegisterTimestamp,proto3" json:"RegisterTimestamp,omitempty"`
}

func (x *AccountRequest) Reset() {
	*x = AccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRequest) ProtoMessage() {}

func (x *AccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRequest.ProtoReflect.Descriptor instead.
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{0}
}

func (x *AccountRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AccountRequest) GetRegisterTimestamp() int64 {
	if x != nil {
		return x.RegisterTimestamp
	}
	return 0
}

type AccountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	RegisterTimestamp int64 `protobuf:"varint,2,opt,name=RegisterTimestamp,proto3" json:"RegisterTimestamp,omitempty"`
}

func (x *AccountReply) Reset() {
	*x = AccountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountReply) ProtoMessage() {}

func (x *AccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountReply.ProtoReflect.Descriptor instead.
func (*AccountReply) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{1}
}

func (x *AccountReply) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AccountReply) GetRegisterTimestamp() int64 {
	if x != nil {
		return x.RegisterTimestamp
	}
	return 0
}

type ProfileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type PlaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input    string `protobuf:"bytes,1,opt,name=Input,proto3" json:"Input,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=Language,proto3" json:"Language,omitempty"`
}

func (x *PlaceRequest) Reset() {
	*x = PlaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceRequest) ProtoMessage() {}

func (x *PlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceRequest.ProtoReflect.Descriptor instead.
func (*PlaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *PlaceRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ProfileReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
}

func (x *ProfileReply) Reset() {
	*x = ProfileReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReply) ProtoMessage() {}

func (x *ProfileReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReply.ProtoReflect.Descriptor instead.
func (*ProfileReply) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{4}
}

func (x *ProfileReply) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ProfileReply) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type PointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Point int64 `protobuf:"varint,2,opt,name=Point,proto3" json:"Point,omitempty"`
}

func (x *PointRequest) Reset() {
	*x = PointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointRequest) ProtoMessage() {}

func (x *PointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointRequest.ProtoReflect.Descriptor instead.
func (*PointRequest) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{5}
}

func (x *PointRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PointRequest) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

type PointReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Point int64 `protobuf:"varint,2,opt,name=Point,proto3" json:"Point,omitempty"`
	Count int64 `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *PointReply) Reset() {
	*x = PointReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointReply) ProtoMessage() {}

func (x *PointReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointReply.ProtoReflect.Descriptor instead.
func (*PointReply) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{6}
}

func (x *PointReply) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PointReply) GetPoint() int64 {
	if x != nil {
		return x.Point
	}
	return 0
}

func (x *PointReply) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PlaceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                 string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	FormattedAddress     string `protobuf:"bytes,2,opt,name=FormattedAddress,proto3" json:"FormattedAddress,omitempty"`
	FormattedPhoneNumber string `protobuf:"bytes,3,opt,name=FormattedPhoneNumber,proto3" json:"FormattedPhoneNumber,omitempty"`
	Icon                 string `protobuf:"bytes,4,opt,name=Icon,proto3" json:"Icon,omitempty"`
	PlaceID              string `protobuf:"bytes,5,opt,name=PlaceID,proto3" json:"PlaceID,omitempty"`
	WeekdayText          string `protobuf:"bytes,6,opt,name=WeekdayText,proto3" json:"WeekdayText,omitempty"`
	Types                string `protobuf:"bytes,7,opt,name=Types,proto3" json:"Types,omitempty"`
	Website              string `protobuf:"bytes,8,opt,name=Website,proto3" json:"Website,omitempty"`
	URL                  string `protobuf:"bytes,9,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *PlaceReply) Reset() {
	*x = PlaceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_haru_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceReply) ProtoMessage() {}

func (x *PlaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_haru_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceReply.ProtoReflect.Descriptor instead.
func (*PlaceReply) Descriptor() ([]byte, []int) {
	return file_proto_haru_proto_rawDescGZIP(), []int{7}
}

func (x *PlaceReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlaceReply) GetFormattedAddress() string {
	if x != nil {
		return x.FormattedAddress
	}
	return ""
}

func (x *PlaceReply) GetFormattedPhoneNumber() string {
	if x != nil {
		return x.FormattedPhoneNumber
	}
	return ""
}

func (x *PlaceReply) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PlaceReply) GetPlaceID() string {
	if x != nil {
		return x.PlaceID
	}
	return ""
}

func (x *PlaceReply) GetWeekdayText() string {
	if x != nil {
		return x.WeekdayText
	}
	return ""
}

func (x *PlaceReply) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

func (x *PlaceReply) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *PlaceReply) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_proto_haru_proto protoreflect.FileDescriptor

var file_proto_haru_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x72, 0x75, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x68, 0x61, 0x72, 0x75, 0x22, 0x4e, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x4c, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x2c, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3c, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x34, 0x0a, 0x0c, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x48, 0x0a, 0x0a, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x92, 0x02, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74,
	0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x32, 0x0a, 0x14, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x14, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x65, 0x64, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x63, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x6c, 0x61, 0x63,
	0x65, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x57, 0x65, 0x65, 0x6b, 0x64, 0x61, 0x79, 0x54, 0x65,
	0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x57, 0x65, 0x65, 0x6b, 0x64, 0x61,
	0x79, 0x54, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x57,
	0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x57, 0x65,
	0x62, 0x73, 0x69, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x32, 0xdb, 0x02, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x31, 0x12, 0x3b, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x68, 0x61, 0x72, 0x75, 0x2e, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x68, 0x61,
	0x72, 0x75, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x14, 0x2e, 0x68, 0x61, 0x72, 0x75, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x68, 0x61, 0x72, 0x75, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x68,
	0x61, 0x72, 0x75, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x68, 0x61, 0x72, 0x75, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x68, 0x61, 0x72, 0x75, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x68, 0x61, 0x72, 0x75, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x09,
	0x49, 0x6e, 0x63, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x68, 0x61, 0x72, 0x75,
	0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x68, 0x61, 0x72, 0x75, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x32, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x12, 0x2e,
	0x68, 0x61, 0x72, 0x75, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x68, 0x61, 0x72, 0x75, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x6f, 0x6a, 0x69, 0x6e, 0x2d, 0x6b, 0x72, 0x2f, 0x68, 0x61, 0x72,
	0x75, 0x2f, 0x63, 0x6d, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_haru_proto_rawDescOnce sync.Once
	file_proto_haru_proto_rawDescData = file_proto_haru_proto_rawDesc
)

func file_proto_haru_proto_rawDescGZIP() []byte {
	file_proto_haru_proto_rawDescOnce.Do(func() {
		file_proto_haru_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_haru_proto_rawDescData)
	})
	return file_proto_haru_proto_rawDescData
}

var file_proto_haru_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_haru_proto_goTypes = []interface{}{
	(*AccountRequest)(nil), // 0: haru.AccountRequest
	(*AccountReply)(nil),   // 1: haru.AccountReply
	(*ProfileRequest)(nil), // 2: haru.ProfileRequest
	(*PlaceRequest)(nil),   // 3: haru.PlaceRequest
	(*ProfileReply)(nil),   // 4: haru.ProfileReply
	(*PointRequest)(nil),   // 5: haru.PointRequest
	(*PointReply)(nil),     // 6: haru.PointReply
	(*PlaceReply)(nil),     // 7: haru.PlaceReply
}
var file_proto_haru_proto_depIdxs = []int32{
	0, // 0: haru.version1.CreateAccount:input_type -> haru.AccountRequest
	2, // 1: haru.version1.GetProfile:input_type -> haru.ProfileRequest
	2, // 2: haru.version1.UpdateProfile:input_type -> haru.ProfileRequest
	5, // 3: haru.version1.GetPoint:input_type -> haru.PointRequest
	5, // 4: haru.version1.IncrPoint:input_type -> haru.PointRequest
	3, // 5: haru.version1.GetPlace:input_type -> haru.PlaceRequest
	1, // 6: haru.version1.CreateAccount:output_type -> haru.AccountReply
	4, // 7: haru.version1.GetProfile:output_type -> haru.ProfileReply
	4, // 8: haru.version1.UpdateProfile:output_type -> haru.ProfileReply
	6, // 9: haru.version1.GetPoint:output_type -> haru.PointReply
	6, // 10: haru.version1.IncrPoint:output_type -> haru.PointReply
	7, // 11: haru.version1.GetPlace:output_type -> haru.PlaceReply
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_haru_proto_init() }
func file_proto_haru_proto_init() {
	if File_proto_haru_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_haru_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_haru_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_haru_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_haru_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_haru_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_haru_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_haru_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PointReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_haru_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_haru_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_haru_proto_goTypes,
		DependencyIndexes: file_proto_haru_proto_depIdxs,
		MessageInfos:      file_proto_haru_proto_msgTypes,
	}.Build()
	File_proto_haru_proto = out.File
	file_proto_haru_proto_rawDesc = nil
	file_proto_haru_proto_goTypes = nil
	file_proto_haru_proto_depIdxs = nil
}
